#!/usr/bin/env bash
# Runs DETACHED alongside the matrix. When all 9 runs have written their .series.json
# (or all run.py processes have gone away), it produces every artefact the report needs
# and drops a sentinel. Deliberately does NO git and NO network: the estate's shared
# working tree is not something a background script should be committing onto, and
# publishing is a human-facing act that belongs to the session, not to a cron.
set -u
cd "$(dirname "$0")/.."
LOG=rig/runlogs/finish.out
exec >> "$LOG" 2>&1
echo "=== finisher started $(date -Is) ==="
DEADLINE=$(( $(date +%s) + 6*3600 ))
while :; do
  n=$(ls rig/logs/*.series.json 2>/dev/null | wc -l)
  alive=$(pgrep -fc 'rig/run.py' 2>/dev/null || echo 0)
  if [ "$n" -ge 9 ]; then echo "all 9 series present at $(date -Is)"; break; fi
  if [ "$alive" -eq 0 ]; then echo "WARNING: no run.py alive but only $n/9 series at $(date -Is)"; break; fi
  if [ "$(date +%s)" -gt "$DEADLINE" ]; then echo "WARNING: 6h deadline hit, $n/9 series"; break; fi
  sleep 60
done
sleep 10
echo "--- plots ---";    python3 rig/plot.py rig/logs rig/plots
echo "--- analysis ---"; python3 rig/analyse.py rig/logs | tee rig/plots/table.txt
python3 - <<'PY' > rig/RESULTS.md
import sys, pathlib, json, glob
sys.path.insert(0, "rig")
from analyse import markdown_table, summarise
print("# CE RIG v0 - results\n")
print("Auto-generated by rig/finish.sh when the matrix landed. Numbers only; the reading is in REPORT.md.\n")
print("## Per-condition means across 3 seeds\n")
print(markdown_table("rig/logs"))
by = summarise("rig/logs")
print("\n## Completeness\n")
print("| run | ticks | parse failures | cost |")
print("|---|---|---|---|")
tot = 0.0
for c in "ABC":
    for r in sorted(by.get(c, []), key=lambda r: r["seed"]):
        tot += r.get("cost_usd") or 0
        print(f"| {c} seed{r['seed']} | {r['ticks']} | {r['parse_failures']} | ${r.get('cost_usd') or 0:.2f} |")
print(f"\n**Total spend: ${tot:.2f}**\n")
print("## Sparklines\n\n```\n" + pathlib.Path("rig/plots/sparklines.txt").read_text() + "```\n")
PY
touch rig/.matrix-done
echo "=== finisher done $(date -Is) ==="
